<?php

namespace Database\Seeders;

use Illuminate\Support\Str;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProdukdanobatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('produk_dan_obats')->insert([
            [
                'nama_dagang'   => 'Paracetamol 500mg',
                'kode'          => 'OBT-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Tablet',
                'harga_dasar'   => 1000,
                'diskon'        => 0,
                'harga_bersih'  => 1000 - (1000 * 0 / 100),
                'stok'          => 500,
                'expired_at'    => '2026-01-01',
                'batch'         => 'B1234',
                'lokasi'        => 'Rak A1',
                'supplier'      => 'PT Farmasi Sehat',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Amoxicillin 250mg',
                'kode'          => 'OBT-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Kapsul',
                'harga_dasar'   => 1500,
                'diskon'        => 0,
                'harga_bersih'  => 1500 - (1500 * 0 / 100),
                'stok'          => 300,
                'expired_at'    => '2025-12-31',
                'batch'         => 'B5678',
                'lokasi'        => 'Rak B2',
                'supplier'      => 'Apotek Jaya Farma',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Cetrizine 10mg',
                'kode'          => 'OBT-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Tablet',
                'harga_dasar'   => 2000,
                'diskon'        => 20,
                'harga_bersih'  => 2000 - (2000 * 20 / 100),
                'stok'          => 400,
                'expired_at'    => '2027-03-15',
                'batch'         => 'B3456',
                'lokasi'        => 'Rak A3',
                'supplier'      => 'PT Generik Nusantara',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Ibuprofen 400mg',
                'kode'          => 'OBT-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Tablet',
                'harga_dasar'   => 2500,
                'diskon'        => 25,
                'harga_bersih'  => 2250 - (2250 * 25 / 100),
                'stok'          => 350,
                'expired_at'    => '2026-11-01',
                'batch'         => 'B6789',
                'lokasi'        => 'Rak A4',
                'supplier'      => 'PT Kimia Farma',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Ranitidine 150mg',
                'kode'          => 'OBT-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Tablet',
                'harga_dasar'   => 1700,
                'diskon'        => 10,
                'harga_bersih'  => 1700 - (1700 * 10 / 100),
                'stok'          => 250,
                'expired_at'    => '2026-08-15',
                'batch'         => 'B2345',
                'lokasi'        => 'Rak A5',
                'supplier'      => 'PT Obat Nusantara',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],

            // --- Produk Kecantikan (5) ---
            [
                'nama_dagang'   => 'Betadine Solution',
                'kode'          => 'PRD-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Cairan',
                'harga_dasar'   => 8000,
                'diskon'        => 50,
                'harga_bersih'  => 8000 - (8000 * 50 / 100),
                'stok'          => 100,
                'expired_at'    => '2027-06-01',
                'batch'         => 'B9012',
                'lokasi'        => 'Rak C3',
                'supplier'      => 'CV Medika Sentosa',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Facial Wash Brightening',
                'kode'          => 'PRD-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Cairan',
                'harga_dasar'   => 25000,
                'diskon'        => 20,
                'harga_bersih'  => 25000 - (25000 * 20 / 100),
                'stok'          => 200,
                'expired_at'    => '2026-09-01',
                'batch'         => 'B7788',
                'lokasi'        => 'Rak D1',
                'supplier'      => 'Beauty Care Indonesia',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Moisturizer Aloe Vera Gel',
                'kode'          => 'PRD-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Gel',
                'harga_dasar'   => 30000,
                'diskon'        => 0,
                'harga_bersih'  => 30000 - (30000 * 0 / 100),
                'stok'          => 150,
                'expired_at'    => '2027-02-28',
                'batch'         => 'B8899',
                'lokasi'        => 'Rak D2',
                'supplier'      => 'Nature Glow',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Sunscreen SPF 50',
                'kode'          => 'PRD-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Cream',
                'harga_dasar'   => 40000,
                'diskon'        => 30,
                'harga_bersih'  => 40000 - (40000 * 30 / 100),
                'stok'          => 120,
                'expired_at'    => '2026-05-20',
                'batch'         => 'B9900',
                'lokasi'        => 'Rak D3',
                'supplier'      => 'SunCare Official',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
            [
                'nama_dagang'   => 'Lip Balm Strawberry',
                'kode'          => 'PRD-' . Str::upper(Str::random(6)),
                'sediaan'       => 'Stick',
                'harga_dasar'   => 15000,
                'diskon'        => 0,
                'harga_bersih'  => 15000 - (15000 * 0 / 100),
                'stok'          => 180,
                'expired_at'    => '2026-12-31',
                'batch'         => 'B2233',
                'lokasi'        => 'Rak D4',
                'supplier'      => 'Glow Cosmetics',
                'created_at'    => now(),
                'updated_at'    => now(),
            ],
        ]);
    }
}
